package object;

import java.io.Serializable;

public class User implements Serializable {

  private static final long serialVersionUID = 1L;
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column sec_user.id
   *
   * @mbggenerated
   */
  private Integer id;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column sec_user.account
   *
   * @mbggenerated
   */
  private String account;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column sec_user.fullname
   *
   * @mbggenerated
   */
  private String fullname;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column sec_user.password
   *
   * @mbggenerated
   */
  private String password;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column sec_user.plain_password
   *
   * @mbggenerated
   */
  private String plainPassword;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column sec_user.salt
   *
   * @mbggenerated
   */
  private String salt;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column sec_user.enabled
   *
   * @mbggenerated
   */
  private Integer enabled;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column sec_user.employee_id
   *
   * @mbggenerated
   */
  private Integer employeeId;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column sec_user.id
   *
   * @return the value of sec_user.id
   * @mbggenerated
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column sec_user.id
   *
   * @param id the value for sec_user.id
   * @mbggenerated
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column sec_user.account
   *
   * @return the value of sec_user.account
   * @mbggenerated
   */
  public String getAccount() {
    return account;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column sec_user.account
   *
   * @param account the value for sec_user.account
   * @mbggenerated
   */
  public void setAccount(String account) {
    this.account = account == null ? null : account.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column sec_user.fullname
   *
   * @return the value of sec_user.fullname
   * @mbggenerated
   */
  public String getFullname() {
    return fullname;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column sec_user.fullname
   *
   * @param fullname the value for sec_user.fullname
   * @mbggenerated
   */
  public void setFullname(String fullname) {
    this.fullname = fullname == null ? null : fullname.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column sec_user.password
   *
   * @return the value of sec_user.password
   * @mbggenerated
   */
  public String getPassword() {
    return password;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column sec_user.password
   *
   * @param password the value for sec_user.password
   * @mbggenerated
   */
  public void setPassword(String password) {
    this.password = password == null ? null : password.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column sec_user.plain_password
   *
   * @return the value of sec_user.plain_password
   * @mbggenerated
   */
  public String getPlainPassword() {
    return plainPassword;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column sec_user.plain_password
   *
   * @param plainPassword the value for sec_user.plain_password
   * @mbggenerated
   */
  public void setPlainPassword(String plainPassword) {
    this.plainPassword = plainPassword == null ? null : plainPassword.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column sec_user.salt
   *
   * @return the value of sec_user.salt
   * @mbggenerated
   */
  public String getSalt() {
    return salt;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column sec_user.salt
   *
   * @param salt the value for sec_user.salt
   * @mbggenerated
   */
  public void setSalt(String salt) {
    this.salt = salt == null ? null : salt.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column sec_user.enabled
   *
   * @return the value of sec_user.enabled
   * @mbggenerated
   */
  public Integer getEnabled() {
    return enabled;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column sec_user.enabled
   *
   * @param enabled the value for sec_user.enabled
   * @mbggenerated
   */
  public void setEnabled(Integer enabled) {
    this.enabled = enabled;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column sec_user.employee_id
   *
   * @return the value of sec_user.employee_id
   * @mbggenerated
   */
  public Integer getEmployeeId() {
    return employeeId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column sec_user.employee_id
   *
   * @param employeeId the value for sec_user.employee_id
   * @mbggenerated
   */
  public void setEmployeeId(Integer employeeId) {
    this.employeeId = employeeId;
  }


  @Override
  public String toString() {
    return "User{" +
            "id=" + id +
            ", account=" + account +
            ", fullname=" + fullname +
            ", password=" + password +
            ", plainPassword=" + plainPassword +
            ", salt=" + salt +
            ", enabled=" + enabled +
            ", employeeId=" + employeeId +
            "}";
  }
}